// src/react-client/src/components/pages/index/todo-list/todo-item/todo-item.tsx
import React, { FC, useState } from 'react'
import s from '../todo-list.module.scss'
import { Todo } from '../../../../../shared/types/todo'

const crossIcon = '/close.svg'
const pencilIcon = '/draw.svg'

type Props = {
  todo: Todo,
  deleteTodo: (id: number) => void
  setTodoTitle: (id: number, title: string) => void
  toggleTodo: (id: number) => void
}

export const TodoItem: FC<Props> = ({ todo, deleteTodo, setTodoTitle, toggleTodo }) => {

  const [isEdit, setIsEdit] = useState<boolean>(false)
  const [newText, setNewText] = useState<string>(todo.title)

  return (
    <div className={`${s.todoItem} ${todo.checked ? s.checked : ''}`}>
      {
        !isEdit
          ? <span onClick={() => toggleTodo(todo.id)} className={s.title}>{todo.title}</span>
          : <input className={s.editableTitle} value={newText} onChange={e => setNewText(e.target.value)} type='text' />
      }
      <div className={s.editTodo}>
        <img className={s.pencilIcon} src={pencilIcon} alt='Изменить' onClick={() => {
          if (isEdit) {
            setTodoTitle(todo.id, newText)
          }
          setIsEdit(p => !p)
        }} />
        <img className={s.crossIcon} src={crossIcon} alt='Удалить' onClick={() => deleteTodo(todo.id)} />
      </div>
    </div>
  )
}

// src/angular-client/src/app/components/todo-item/todo-item.component.ts
import { Component, Input, OnInit } from '@angular/core'
import { Todo } from '../../shared/types/todo'
import { TodoService } from '../../services/todo.service'
import { FormBuilder, FormControl, Validators } from '@angular/forms'

@Component({
  selector: 'todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.scss'],
})
export class TodoItemComponent implements OnInit {

  @Input()
  todo!: Todo

  public isEdit = false
  public updateTodoTitleInput!: FormControl

  toggleIsEdit() {
    this.isEdit = !this.isEdit
  }

  submitAndStopEdit() {
    this.todoService.setTodoTitle(this.todo.id, this.updateTodoTitleInput.value)
    this.toggleIsEdit()
  }

  constructor(public readonly todoService: TodoService, private readonly fb: FormBuilder) {
  }


  ngOnInit(): void {
    this.updateTodoTitleInput = this.fb.control(this.todo.title, Validators.required)
  }

}

<div [ngClass]='{checked: todo.checked, todoItem: true}'>
  <span (click)='todoService.toggleTodoChecked(todo.id)'
        *ngIf='!isEdit;else editableTitle'
        class='title'
  >{{todo.title}}</span>
  <ng-template #editableTitle><input [formControl]='updateTodoTitleInput' type='text' class='editableTitle'>
  </ng-template>
  <div class='editTodo'>
    <img (click)='isEdit ? submitAndStopEdit() : toggleIsEdit()' class='pencilIcon' src='./assets/images/draw.svg'
         alt='Изменить' />
    <img (click)='todoService.deleteTodo(todo.id)' class='crossIcon' src='./assets/images/close.svg' alt='Удалить' />
  </div>
</div>
