// src/react-client/src/components/common/header/header.tsx
import React from 'react'
import { Link } from 'react-router-dom'
import reactLogo from '../../../shared/images/react-icon.svg'
import angularLogo from '../../../shared/images/angular-icon.svg'
import { Container } from '../container/container'
import s from './header.module.scss'

const Header = () => {
  return (
    <div className={s.header}>
      <Container>
        <ul className={s.list}>
          <li className={s.item}><Link to={'./react'} className={s.link}>
            <img className={s.reactLogo} src={reactLogo} alt='Реакт' />
          </Link></li>
          <li className={s.item}>
            <h2 className={s.title}>Todo-List</h2>
          </li>
          <li className={s.item}><Link className={s.link} to={'./angular'}><img className={s.angularLogo} src={angularLogo} alt='angular' /></Link></li>
        </ul>
      </Container>
    </div>
  )
}

export default Header

// src/angular-client/src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { environment } from '../../../environments/environment'

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  reactUrl: string = environment.reactAppUrl

  constructor() { }

  ngOnInit(): void {
  }

}

<div class='header'>
  <div class='container'>
    <ul class='list'>
      <li class='item'><a href='#' class='link' [href]=reactUrl>
        <img class='reactLogo' src='/assets/images/react-icon.svg' alt='Реакт' />
      </a></li>
      <li class='item'>
        <h2 class='title'>Todo-List</h2>
      </li>
      <li class='item'>
        <a class='link'>
          <img class='angularLogo' src='/assets/images/angular-icon.svg' alt='angular' />
        </a>
      </li>
    </ul>
  </div>
</div>
